version: '3.8'
services:
  web:
    image: nginx:1.21.1-alpine
    container_name: nginx
    restart: always
    ports:
      - "3001:80"
    volumes:
      - ./app:/app
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/site.conf
    links:
      - fpm
  fpm:
    build: ./docker/fpm
    container_name: fpm
    volumes:
      - ./app:/app
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_HOST: ${DB_HOST}
    depends_on:
      - postgres
  cli:
    build: ./docker/cli
    container_name: cli
    restart: "no"
    volumes:
      - ./app:/app
    working_dir: /app
  composer:
    image: composer:2.2.6
    container_name: composer
    command: composer install --prefer-dist --no-progress
    environment:
      - ./app/var/cache/composer=/app/var/cache/composer
    volumes:
      - ./app:/app
    restart: "no"
  postgres:
    container_name: postgres
    image: postgres:11-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - /docker/postgres/data:/var/lib/postgresql/data



      

